### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by njittam** [RSDT/bot2#15]
er is een error opgetreden:
 update
Expecting value: line 1 column 1 (char 0)

**Comment by njittam** [comment]
<class 'ValueError'>
 Traceback (most recent call last):
  File "/home/david/bot2/Updates.py", line 158, in call
    func(_args, *_kwargs)
  File "/home/david/bot2/Updates.py", line 668, in update
    new_item = self.get_item_callback()
  File "/home/david/bot2/Updates.py", line 263, in <lambda>
    get_last_hint = lambda: jotihuntApi.get_hints().data[0]
  File "/home/david/bot2/PythonApi/jotihunt/Retrievers.py", line 204, in get_hints
    return Response(r.json(), HINTS)
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/**init**.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by njittam** [comment]
ik hoop dat dit komt omdat er geen hints zijn op dit moment.

**Comment by njittam** [comment]
de Joitihunt api geeft op dit moment niks terug

**Comment by njittam** [comment]
fixed
