### ISSUE TITLE
b' 401 : Unauthorized || ERROR 110 : GEEN GELDIGE SLEUTEL IN GEVOERD.'

### ISSUE THREAD

**Issue by njittam** [RSDT/bot2#18]
er is een error opgetreden:
 update
b' 401 : Unauthorized || ERROR 110 : GEEN GELDIGE SLEUTEL IN GEVOERD.'

**Comment by njittam** [comment]
semi autofix al  gedaan

**Comment by njittam** [comment]
er is een error opgetreden:
 update
b' 401 : Unauthorized || ERROR 110 : GEEN GELDIGE SLEUTEL IN GEVOERD.'
<class 'PythonApi.Base.Exceptions.VerificationError'>
Traceback (most recent call last):
  File "/home/mattijn/projects/jotihunt/bot2/PythonApi/RPApi/Base.py", line 17, in decorate
    return func(self, _args, *_kwargs)
  File "/home/mattijn/projects/jotihunt/bot2/PythonApi/RPApi/Base.py", line 60, in _send_request
    raise VerificationError(r.content)
PythonApi.Base.Exceptions.VerificationError: b' 401 : Unauthorized || ERROR 110 : GEEN GELDIGE SLEUTEL IN GEVOERD.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mattijn/projects/jotihunt/bot2/Updates.py", line 158, in call
    func(_args, *_kwargs)
  File "/home/mattijn/projects/jotihunt/bot2/Updates.py", line 666, in update
    new_item = self.get_item_callback()
  File "/home/mattijn/projects/jotihunt/bot2/Updates.py", line 225, in retriever
    return self.rp_api.vos(dg)
  File "/home/mattijn/projects/jotihunt/bot2/PythonApi/RPApi/Base.py", line 114, in vos
    result = self._vos_last(team)
  File "/home/mattijn/projects/jotihunt/bot2/PythonApi/RPApi/Base.py", line 126, in _vos_last
    data = self._send_request(root, functie)
  File "/home/mattijn/projects/jotihunt/bot2/PythonApi/RPApi/Base.py", line 20, in decorate
    return func(self, _args, *_kwargs)
  File "/home/mattijn/projects/jotihunt/bot2/PythonApi/RPApi/Base.py", line 60, in _send_request
    raise VerificationError(r.content)
PythonApi.Base.Exceptions.VerificationError: b' 401 : Unauthorized || ERROR 110 : GEEN GELDIGE SLEUTEL IN GEVOERD.'

**Comment by njittam** [comment]
- root - ERROR - Login error, return TrueExpecting value: line 1 column 1 (char 0), 60
